// Mock data for Optra application

export const mockOpportunities = [
  {
    id: "1",
    title: "Full-Stack Engineer Intern",
    company: "Sarvam AI",
    type: "internship",
    location: "Bangalore (Remote OK)",
    stipend: "₹40,000/mo",
    deadline: "2026-08-10",
    daysLeft: 19,
    matchScore: 94,
    tags: ["React", "Python", "LLMs", "FastAPI"],
    source: "YC Jobs",
    logo: "S",
    color: "#6366F1",
    description: "Work on cutting-edge language model infrastructure for Indian languages.",
    verified: true,
    applicants: 234,
  },
  {
    id: "2",
    title: "ETHIndia 2026 Hackathon",
    company: "Devfolio",
    type: "hackathon",
    location: "Bangalore",
    stipend: "$5,000 prize pool",
    deadline: "2026-08-05",
    daysLeft: 14,
    matchScore: 88,
    tags: ["Web3", "Solidity", "React", "DeFi"],
    source: "Devfolio",
    logo: "E",
    color: "#06B6D4",
    description: "India's largest Ethereum hackathon. Build, ship, and win.",
    verified: true,
    applicants: 1200,
  },
  {
    id: "3",
    title: "Google Summer of Code 2026",
    company: "Google Open Source",
    type: "grant",
    location: "Remote",
    stipend: "$3,000–$6,600",
    deadline: "2026-08-20",
    daysLeft: 29,
    matchScore: 79,
    tags: ["Open Source", "Python", "ML", "Community"],
    source: "GSoC Portal",
    logo: "G",
    color: "#10B981",
    description: "Contribute to open-source organizations with Google's support.",
    verified: true,
    applicants: 45000,
  },
  {
    id: "4",
    title: "ISRO Scientist/Engineer SC",
    company: "ISRO",
    type: "exam",
    location: "All India",
    stipend: "₹56,100/mo + DA",
    deadline: "2026-08-15",
    daysLeft: 24,
    matchScore: 71,
    tags: ["GATE", "Electronics", "CS", "Government"],
    source: "ISRO Portal",
    logo: "I",
    color: "#F59E0B",
    description: "Join India's premier space research organization.",
    verified: true,
    applicants: 89000,
  },
  {
    id: "5",
    title: "Backend Developer — Startup",
    company: "Supermind AI",
    type: "job",
    location: "Remote",
    stipend: "₹8–14 LPA",
    deadline: "2026-07-30",
    daysLeft: 8,
    matchScore: 91,
    tags: ["Node.js", "PostgreSQL", "Redis", "Docker"],
    source: "Twitter/X",
    logo: "S",
    color: "#8B5CF6",
    description: "Build scalable backend for AI-powered productivity tools.",
    verified: false,
    applicants: 47,
  },
  {
    id: "6",
    title: "ML Research Fellowship",
    company: "IIT Bombay AI Lab",
    type: "grant",
    location: "Mumbai",
    stipend: "₹25,000/mo",
    deadline: "2026-09-01",
    daysLeft: 41,
    matchScore: 82,
    tags: ["PyTorch", "Research", "NLP", "CV"],
    source: "University Portal",
    logo: "I",
    color: "#10B981",
    description: "6-month research fellowship under Professor in AI/ML domain.",
    verified: true,
    applicants: 120,
  },
  {
    id: "7",
    title: "Smart India Hackathon 2026",
    company: "MoE — Government of India",
    type: "hackathon",
    location: "Pan India",
    stipend: "₹1,00,000 prize",
    deadline: "2026-08-25",
    daysLeft: 34,
    matchScore: 76,
    tags: ["GovTech", "AI", "Social Impact", "Fullstack"],
    source: "SIH Portal",
    logo: "S",
    color: "#06B6D4",
    description: "National hackathon solving real government problem statements.",
    verified: true,
    applicants: 500000,
  },
  {
    id: "8",
    title: "GATE CS 2027",
    company: "IIT Roorkee (Organizing)",
    type: "exam",
    location: "All India",
    stipend: "Gateway to PSU & M.Tech",
    deadline: "2026-09-15",
    daysLeft: 55,
    matchScore: 68,
    tags: ["CS", "Algorithms", "OS", "Networks"],
    source: "GATE Portal",
    logo: "G",
    color: "#F59E0B",
    description: "Graduate Aptitude Test in Engineering — your gateway to top institutes.",
    verified: true,
    applicants: 900000,
  },
];

export const mockStudentProfile = {
  name: "Rahul Sharma",
  avatar: "RS",
  college: "VIT Vellore",
  year: "3rd Year",
  branch: "CSE",
  cgpa: "8.4",
  verified: true,
  optraScore: 782,
  matchScore: 87,
  skills: [
    { name: "React", level: 88 },
    { name: "Python", level: 75 },
    { name: "Node.js", level: 80 },
    { name: "TypeScript", level: 70 },
    { name: "SQL", level: 65 },
    { name: "Docker", level: 45 },
    { name: "ML/AI", level: 55 },
    { name: "System Design", level: 40 },
  ],
  achievements: [
    { title: "Hackathon Winner", desc: "ETHIndia 2025 — DeFi Track", icon: "🏆" },
    { title: "Open Source Contributor", desc: "50+ merged PRs on GitHub", icon: "⭐" },
    { title: "Verified CGPA 8.4", desc: "DigiLocker Verified", icon: "✅" },
  ],
  applications: [
    { company: "Sarvam AI", role: "Full-Stack Intern", status: "under_review", date: "2026-07-18" },
    { company: "Supermind AI", role: "Backend Dev", status: "interview_scheduled", date: "2026-07-15" },
    { company: "GSoC", role: "Open Source Grant", status: "applied", date: "2026-07-10" },
    { company: "ETHIndia", role: "Hackathon Team", status: "accepted", date: "2026-07-08" },
  ],
  roadmap: [
    { task: "Build a full-stack AI project with LLM APIs", done: true, priority: "high" },
    { task: "Deploy on Vercel + set up CI/CD pipeline", done: true, priority: "medium" },
    { task: "Add Docker containerization to your project", done: false, priority: "high" },
    { task: "Learn basic system design (HLD diagrams)", done: false, priority: "high" },
    { task: "Solve 50 LeetCode Medium problems", done: false, priority: "medium" },
  ],
};

export const mockScoutActivity = [
  { time: "Just now", source: "Twitter/X", event: "Found: Remote React internship @ ZenML — ₹35,000/mo", type: "new", matchedStudents: 32 },
  { time: "2m ago", source: "Devfolio", event: "New Hackathon: Build on Blockchain India — $2,000 prize", type: "new", matchedStudents: 89 },
  { time: "5m ago", source: "YC Jobs", event: "Updated: Sarvam AI increased stipend to ₹45,000/mo", type: "update", matchedStudents: 0 },
  { time: "12m ago", source: "ISRO Portal", event: "Deadline reminder: ISRO Scientist SC — 24 days left", type: "alert", matchedStudents: 156 },
  { time: "18m ago", source: "GSoC Portal", event: "New org added: Rust Foundation (systems, compilers)", type: "new", matchedStudents: 21 },
  { time: "31m ago", source: "University Portal", event: "Found: IIT Delhi RA position — Prof. Amitabh Singh, NLP", type: "new", matchedStudents: 14 },
  { time: "45m ago", source: "Telegram", event: "Scraped 12 new hiring posts from t.me/remoteindiajobs", type: "new", matchedStudents: 67 },
  { time: "1h ago", source: "GitHub", event: "Trending repo: open-source bounty — $500 for PR #241", type: "new", matchedStudents: 8 },
];

export const mockVerification = {
  digilocker: {
    connected: true,
    documents: [
      { name: "10th Marksheet", issuer: "CBSE", verified: true, score: "94.4%" },
      { name: "12th Marksheet", issuer: "CBSE", verified: true, score: "89.2%" },
      { name: "B.Tech Semester Marksheets", issuer: "VIT Vellore", verified: true, score: "CGPA 8.4" },
      { name: "APAAR/ABC ID", issuer: "Ministry of Education", verified: true, score: "ID: APAAR-2023-XXXX" },
    ],
  },
  faceVerification: {
    completed: true,
    score: 99.2,
    lastVerified: "2026-07-20",
    livenessCheck: true,
  },
  optraScore: {
    total: 782,
    breakdown: [
      { label: "Academic Credentials", score: 210, max: 250, color: "#6366F1" },
      { label: "Hackathon Wins", score: 180, max: 200, color: "#06B6D4" },
      { label: "GitHub Activity", score: 142, max: 200, color: "#10B981" },
      { label: "Roadmap Completion", score: 130, max: 200, color: "#F59E0B" },
      { label: "Verification Trust", score: 120, max: 150, color: "#8B5CF6" },
    ],
  },
};

export const mockRecruiters = [
  {
    id: "r1",
    name: "Priya Mehta",
    company: "Sarvam AI",
    role: "Engineering Lead",
    verified_candidates_viewed: 45,
    hired: 3,
    openings: ["Full-Stack Intern", "ML Engineer"],
  },
];

export const mockCandidates = [
  {
    id: "c1",
    name: "Rahul Sharma",
    college: "VIT Vellore",
    cgpa: "8.4",
    optraScore: 782,
    skills: ["React", "Node.js", "Python", "TypeScript"],
    verified: true,
    hackathonWins: 2,
    githubStars: 234,
    matchRole: 94,
  },
  {
    id: "c2",
    name: "Anjali Singh",
    college: "BITS Pilani",
    cgpa: "9.1",
    optraScore: 851,
    skills: ["Python", "ML", "PyTorch", "FastAPI"],
    verified: true,
    hackathonWins: 3,
    githubStars: 512,
    matchRole: 91,
  },
  {
    id: "c3",
    name: "Arjun Patel",
    college: "IIIT Hyderabad",
    cgpa: "8.8",
    optraScore: 810,
    skills: ["Go", "Kubernetes", "Docker", "System Design"],
    verified: true,
    hackathonWins: 1,
    githubStars: 187,
    matchRole: 88,
  },
  {
    id: "c4",
    name: "Sneha Reddy",
    college: "NIT Warangal",
    cgpa: "8.6",
    optraScore: 795,
    skills: ["React", "Vue", "GraphQL", "Figma"],
    verified: false,
    hackathonWins: 4,
    githubStars: 320,
    matchRole: 85,
  },
  {
    id: "c5",
    name: "Karthik Nair",
    college: "PSG Tech Coimbatore",
    cgpa: "7.9",
    optraScore: 740,
    skills: ["Java", "Spring Boot", "MySQL", "AWS"],
    verified: true,
    hackathonWins: 1,
    githubStars: 98,
    matchRole: 79,
  },
];
