// Mock data for Optra application featuring live LinkedIn & Unstop APIs

export const mockOpportunities = [
  {
    id: "li-1",
    title: "AI Engineer & Full-Stack Developer",
    company: "Google India",
    type: "job",
    location: "Bangalore / Hybrid",
    stipend: "₹18–25 LPA",
    deadline: "2026-08-15",
    daysLeft: 24,
    matchScore: 96,
    tags: ["React", "Python", "TensorFlow", "FastAPI"],
    source: "LinkedIn",
    logo: "G",
    color: "#4285F4",
    description: "Build next-generation generative AI products on Google Cloud infrastructure.",
    verified: true,
    applicants: 420,
    url: "https://linkedin.com/jobs/view/google-ai-dev",
  },
  {
    id: "un-1",
    title: "Unstop National Tech Challenge 2026",
    company: "Tata Consultancy Services (Unstop)",
    type: "hackathon",
    location: "Pan-India Online",
    stipend: "₹5,000,000 Prize + PPI",
    deadline: "2026-08-12",
    daysLeft: 21,
    matchScore: 92,
    tags: ["Fullstack", "Problem Solving", "System Architecture"],
    source: "Unstop",
    logo: "U",
    color: "#007BFF",
    description: "National flagship coding challenge for CS students with direct job offers.",
    verified: true,
    applicants: 14500,
    url: "https://unstop.com/competitions/tech-challenge-2026",
  },
  {
    id: "li-2",
    title: "Frontend Engineer Intern (React/Next.js)",
    company: "Microsoft India",
    type: "internship",
    location: "Hyderabad",
    stipend: "₹50,000/mo",
    deadline: "2026-08-10",
    daysLeft: 19,
    matchScore: 94,
    tags: ["React", "TypeScript", "TailwindCSS", "Next.js"],
    source: "LinkedIn",
    logo: "M",
    color: "#00A4EF",
    description: "Design accessible, highly performant web applications for Azure platform.",
    verified: true,
    applicants: 310,
    url: "https://linkedin.com/jobs/view/microsoft-frontend-intern",
  },
  {
    id: "un-2",
    title: "Flipkart GRiD 7.0 Software Development Track",
    company: "Flipkart (Unstop)",
    type: "hackathon",
    location: "Bangalore",
    stipend: "₹1,500,000 Prize + Interview Call",
    deadline: "2026-08-08",
    daysLeft: 17,
    matchScore: 90,
    tags: ["DSA", "E-Commerce", "Scalability", "Node.js"],
    source: "Unstop",
    logo: "F",
    color: "#F6A800",
    description: "Solve e-commerce supply chain challenges and compete with India's top coders.",
    verified: true,
    applicants: 89000,
    url: "https://unstop.com/hackathons/flipkart-grid-7",
  },
  {
    id: "li-3",
    title: "Backend Engineer (Node.js & Python)",
    company: "Sarvam AI",
    type: "internship",
    location: "Bangalore (Remote OK)",
    stipend: "₹45,000/mo",
    deadline: "2026-08-10",
    daysLeft: 19,
    matchScore: 94,
    tags: ["React", "Python", "LLMs", "FastAPI"],
    source: "LinkedIn",
    logo: "S",
    color: "#6366F1",
    description: "Work on cutting-edge language model infrastructure for Indian languages.",
    verified: true,
    applicants: 234,
    url: "https://linkedin.com/jobs/view/sarvam-ai-intern",
  },
  {
    id: "un-3",
    title: "Uber HackTag 2026 AI Edition",
    company: "Uber Engineering (Unstop)",
    type: "hackathon",
    location: "Remote",
    stipend: "₹2,000,000 Pool + Internship",
    deadline: "2026-08-22",
    daysLeft: 30,
    matchScore: 88,
    tags: ["Microservices", "Python", "AI Routing", "Go"],
    source: "Unstop",
    logo: "U",
    color: "#000000",
    description: "Build real-time routing and AI dispatch systems for mobility.",
    verified: true,
    applicants: 22000,
    url: "https://unstop.com/hackathons/uber-hacktag-2026",
  },
  {
    id: "li-4",
    title: "Software Engineer — New Grad 2026",
    company: "Amazon Web Services",
    type: "job",
    location: "Bangalore",
    stipend: "₹28–32 LPA",
    deadline: "2026-08-30",
    daysLeft: 38,
    matchScore: 85,
    tags: ["Java", "Distributed Systems", "AWS", "Linux"],
    source: "LinkedIn",
    logo: "A",
    color: "#FF9900",
    description: "Build high-throughput distributed services powering Amazon Cloud.",
    verified: true,
    applicants: 1200,
    url: "https://linkedin.com/jobs/view/aws-sde-1",
  },
  {
    id: "opt-1",
    title: "Verified Optra Full-Stack Developer",
    company: "Supermind AI",
    type: "job",
    location: "Remote",
    stipend: "₹10–16 LPA",
    deadline: "2026-07-30",
    daysLeft: 8,
    matchScore: 95,
    tags: ["Node.js", "PostgreSQL", "Redis", "Docker"],
    source: "Verified Optra Direct",
    logo: "O",
    color: "#8B5CF6",
    description: "Direct fast-track hiring for Optra Verified candidates with Face ID score > 750.",
    verified: true,
    applicants: 47,
    url: "/explore",
  },
];

export const mockStudentProfile = {
  name: "Rahul Sharma",
  avatar: "RS",
  college: "VIT Vellore",
  year: "3rd Year",
  branch: "CSE",
  cgpa: "8.4",
  verified: true,
  optraScore: 782,
  matchScore: 87,
  skills: [
    { name: "React", level: 88 },
    { name: "Python", level: 75 },
    { name: "Node.js", level: 80 },
    { name: "TypeScript", level: 70 },
    { name: "SQL", level: 65 },
    { name: "Docker", level: 45 },
    { name: "ML/AI", level: 55 },
    { name: "System Design", level: 40 },
  ],
  achievements: [
    { title: "Hackathon Winner", desc: "ETHIndia 2025 — DeFi Track", icon: "🏆" },
    { title: "Open Source Contributor", desc: "50+ merged PRs on GitHub", icon: "⭐" },
    { title: "Verified CGPA 8.4", desc: "DigiLocker Verified", icon: "✅" },
  ],
  applications: [
    { company: "Sarvam AI", role: "Full-Stack Intern", status: "under_review", date: "2026-07-18" },
    { company: "Microsoft", role: "Frontend Intern", status: "interview_scheduled", date: "2026-07-15" },
    { company: "Google India", role: "AI Engineer", status: "applied", date: "2026-07-10" },
    { company: "Flipkart GRiD", role: "Hackathon Team", status: "accepted", date: "2026-07-08" },
  ],
  roadmap: [
    { task: "Build a full-stack AI project with LLM APIs", done: true, priority: "high" },
    { task: "Deploy on Vercel + set up CI/CD pipeline", done: true, priority: "medium" },
    { task: "Add Docker containerization to your project", done: false, priority: "high" },
    { task: "Learn basic system design (HLD diagrams)", done: false, priority: "high" },
    { task: "Solve 50 LeetCode Medium problems", done: false, priority: "medium" },
  ],
};

export const mockScoutActivity = [
  { time: "Just now", source: "LinkedIn API", event: "Scraped 15 active React/AI developer roles from LinkedIn Jobs", type: "new", matchedStudents: 42 },
  { time: "2m ago", source: "Unstop API", event: "New Competition: Flipkart GRiD 7.0 now open — ₹15 Lakh prize", type: "new", matchedStudents: 89 },
  { time: "5m ago", source: "WhatsApp Gateway", event: "Sent instant verification OTP via WhatsApp to +91 98765 43210", type: "update", matchedStudents: 1 },
  { time: "12m ago", source: "Google Cloud", event: "Verified biometric face scan for candidate Rahul Sharma", type: "alert", matchedStudents: 1 },
  { time: "18m ago", source: "LinkedIn API", event: "Matched Sarvam AI stipend increase to ₹45,000/mo", type: "new", matchedStudents: 21 },
  { time: "31m ago", source: "Unstop API", event: "Uber HackTag 2026 AI Registration deadline updated — 30 days left", type: "new", matchedStudents: 67 },
];

export const mockVerification = {
  digilocker: {
    connected: true,
    documents: [
      { name: "10th Marksheet", issuer: "CBSE", verified: true, score: "94.4%" },
      { name: "12th Marksheet", issuer: "CBSE", verified: true, score: "89.2%" },
      { name: "B.Tech Semester Marksheets", issuer: "VIT Vellore", verified: true, score: "CGPA 8.4" },
      { name: "APAAR/ABC ID", issuer: "Ministry of Education", verified: true, score: "ID: APAAR-2023-XXXX" },
    ],
  },
  faceVerification: {
    completed: true,
    score: 99.2,
    lastVerified: "2026-07-22",
    livenessCheck: true,
  },
  optraScore: {
    total: 782,
    breakdown: [
      { label: "Academic Credentials", score: 210, max: 250, color: "#4285F4" },
      { label: "Hackathon Wins", score: 180, max: 200, color: "#007BFF" },
      { label: "GitHub Activity", score: 142, max: 200, color: "#34A853" },
      { label: "Roadmap Completion", score: 130, max: 200, color: "#FBBC05" },
      { label: "Verification Trust", score: 120, max: 150, color: "#EA4335" },
    ],
  },
};

export const mockRecruiters = [
  {
    id: "r1",
    name: "Priya Mehta",
    company: "Sarvam AI",
    role: "Engineering Lead",
    verified_candidates_viewed: 45,
    hired: 3,
    openings: ["Full-Stack Intern", "ML Engineer"],
  },
];

export const mockCandidates = [
  {
    id: "c1",
    name: "Rahul Sharma",
    college: "VIT Vellore",
    cgpa: "8.4",
    optraScore: 782,
    skills: ["React", "Node.js", "Python", "TypeScript"],
    verified: true,
    hackathonWins: 2,
    githubStars: 234,
    matchRole: 94,
  },
  {
    id: "c2",
    name: "Anjali Singh",
    college: "BITS Pilani",
    cgpa: "9.1",
    optraScore: 851,
    skills: ["Python", "ML", "PyTorch", "FastAPI"],
    verified: true,
    hackathonWins: 3,
    githubStars: 512,
    matchRole: 91,
  },
  {
    id: "c3",
    name: "Arjun Patel",
    college: "IIIT Hyderabad",
    cgpa: "8.8",
    optraScore: 810,
    skills: ["Go", "Kubernetes", "Docker", "System Design"],
    verified: true,
    hackathonWins: 1,
    githubStars: 187,
    matchRole: 88,
  },
  {
    id: "c4",
    name: "Sneha Reddy",
    college: "NIT Warangal",
    cgpa: "8.6",
    optraScore: 795,
    skills: ["React", "Vue", "GraphQL", "Figma"],
    verified: false,
    hackathonWins: 4,
    githubStars: 320,
    matchRole: 85,
  },
  {
    id: "c5",
    name: "Karthik Nair",
    college: "PSG Tech Coimbatore",
    cgpa: "7.9",
    optraScore: 740,
    skills: ["Java", "Spring Boot", "MySQL", "AWS"],
    verified: true,
    hackathonWins: 1,
    githubStars: 98,
    matchRole: 79,
  },
];
